export enum ActionTypes {
  GET_FILMS = "GET_FILMS",
  GET_FILM = "GET_FILM",
  GET_FILMS_PAGINATED = "GET_FILMS_PAGINATED",
  GET_FILMS_EXCLUDE_SERIES = "GET_FILMS_EXCLUDE_SERIES",
  UPDATE_FILM = "UPDATE_FILM",
}
