export enum MutationTypes {
  SET_FILMS = "SET_FILMS",
  SET_FILM = "SET_FILM",
  SET_LOADING = "SET_LOADING",
  SET_FILM_DATA = "SET_FILM_DATA",
  SET_FILMS_PAGINATION = "SET_FILMS_PAGINATION",
  SET_FILMS_EXCLUDE_SERIES = "SET_FILMS_EXCLUDE_SERIES",
}
