export enum MutationTypes {
  SET_COMMENT_ASSETS = "SET_COMMENT_ASSETS",
  SET_COMMENT_ASSET = "SET_COMMENT_ASSET",
  SET_LOADING = "SET_LOADING",
  SET_COMMENT_ASSETS_PAGINATION = "SET_COMMENT_ASSETS_PAGINATION",
}
