export enum ActionTypes {
  GET_FEEDBACKS = "GET_FEEDBACKS",
  DELETE_FEEDBACK = "DELETE_FEEDBACK",
  CREATE_FEEDBACK = "CREATE_FEEDBACK",
  UPDATE_FEEDBACK = "UPDATE_FEEDBACK",
  GET_FEEDBACK_BY_FILM_ID = "GET_FEEDBACK_BY_FILM_ID",
}
