export enum MutationTypes {
  SET_FEEDBACKS = "SET_FEEDBACKS",
  SET_LOADING = "SET_LOADING",
  SET_FEEDBACKS_PAGINATION = "SET_FEEDBACKS_PAGINATION",
  UPDATE_NEW_FEEDBACK_DATA = "UPDATE_NEW_FEEDBACK_DATA",
  SET_EDIT_FEEDBACK_DATA = "SET_EDIT_FEEDBACK_DATA",
  SET_FEEDBACK = "SET_FEEDBACK",
}
