export enum ActionTypes {
  GET_SERIES = "GET_SERIES",
  GET_SERIES_ARRAY = "GET_SERIES_ARRAY",
  CREATE_SERIES = "CREATE_SERIES",
  UPDATE_SERIES = "UPDATE_SERIES",
  DELETE_SERIES = "DELETE_SERIES",
}
