export enum ActionTypes {
  SIGN_IN = "SIGN_IN",
  SIGN_UP = "SIGN_UP",
  VERIFY = "VERIFY",
  AUTO_SIGN_IN = "AUTO_SIGN_IN",
  UPDATE_USER_SECURITY = "UPDATE_USER_SECURITY",
  ME = "ME",
  LOGOUT = "LOGOUT",
}
