export enum MutationTypes {
  SET_JWT_TOKEN = "SET_JWT_TOKEN",
  SET_USER = "SET_USER",
  SET_LOGIN_DATA = "SET_LOGIN_DATA",
  SET_SIGN_UP_DATA = "SET_SIGN_UP_DATA",
  SET_HAS_USER = "SET_HAS_USER",
}
