export enum ActionTypes {
  GET_COMMENTS_BY_FILM_ID = "GET_COMMENTS_BY_FILM_ID",
  GET_COMMENT = "GET_COMMENT",
  CREATE_COMMENT = "CREATE_COMMENT",
  UPDATE_COMMENT = "UPDATE_COMMENT",
  DELETE_COMMENT = "DELETE_COMMENT",
  LIKE_COMMENT = "LIKE_COMMENT",
}
