export enum MutationTypes {
  SET_COMMENTS = "SET_COMMENTS",
  SET_COMMENT = "SET_COMMENT",
  SET_LOADING = "SET_LOADING",
  SET_COMMENTS_PAGINATION = "SET_COMMENTS_PAGINATION",
  UPDATE_NEW_COMMENT_DATA = "UPDATE_NEW_COMMENT_DATA",
}
