export enum ActionTypes {
  GET_ADMINS = "GET_ADMINS",
  GET_ADMIN = "GET_ADMIN",
  UPDATE_ADMIN = "UPDATE_ADMIN",
  PUBLISH_ADMIN = "PUBLISH_ADMIN",
  HARD_DELETE_ADMIN = "HARD_DELETE_ADMIN",
  DELETE_ADMIN = "DELETE_ADMIN",
  UPDATE_ADMIN_AVATAR = "UPDATE_ADMIN_AVATAR",
  CREATE_USER = "CREATE_USER",
}
