export enum MutationTypes {
  SET_ADMINS = "SET_ADMINS",
  SET_ADMIN = "SET_ADMIN",
  SET_LOADING = "SET_LOADING",
  SET_ADMINS_PAGINATION = "SET_ADMINS_PAGINATION",
  UPDATE_SECURITY_DATA = "UPDATE_SECURITY_DATA",
  UPDATE_ADMIN_DATA = "UPDATE_ADMIN_DATA",
}
